name: Deploy Laier Functions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Func Tools
      run: |
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4 -y

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v2
      with:
        app-name: ${{ secrets.FUNCTIONAPP_NAME }}
        package: '.'
